name: pspdfkit_example
description: Demonstrates how to use the pspdfkit plugin.
version: 3.12.0
homepage: https://pspdfkit.com/
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.16.9'

dependencies:
  flutter:
    sdk: flutter  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  http: ^0.13.5
  url_launcher: ^6.1.10
  pspdfkit_flutter: any

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - PDFs/
    - PDFs/Instant/
